//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOS
    {
        public int ID_EMPLEADO { get; set; }
        public string DESCRIPCION { get; set; }
        public string GENERO_SEXO { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public int ID_DEPARTAMENTO { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual DEPARTAMENTOS DEPARTAMENTOS { get; set; }
    }
}
